### ISSUE TITLE
getCols and getRows

### ISSUE THREAD

**Issue by GregorySchwartz** [chessai/eigen#11]
What happened to these functions?

**Comment by chessai** [comment]
I just added them in the following commit: bf78bf8b663d3955a9edab82e23cb62b83353bd6

Apologies for that. The refactor of `eigen` was all-encompassing. If there are any other functions you notice missing, please let me know!

Also, do you need a release with these functions re-added?

**Comment by GregorySchwartz** [comment]
What about fromCols and fromRows?

**Comment by chessai** [comment]
> What about fromCols and fromRows?

Just added in 8b63753

**Comment by chessai** [comment]
Closing in favour of https://github.com/chessai/eigen/issues/12
