### ISSUE TITLE
Can Haskell bindings be updated to use Eigen 3.3.5 version ?

### ISSUE THREAD

**Issue by vincent-hui** [chessai/eigen#13]
Eigen 3.3.5 was released. Can Haskell bindings be updated to use Eigen 3.3.5 version ?

**Comment by chessai** [comment]
Yes, this is on my to-do list. Thank you for opening this issue.

**Comment by vincent-hui** [comment]
3.3.6 released http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.6
Can Haskell bindings be updated to use Eigen 3.3.6 version ?
Thanks

**Comment by chessai** [comment]
i'm actually going to update to 3.3.7

**Comment by chessai** [comment]
eigen 3.3.7 is now on hackage.
